name: GuideUI
main: NZS\ND\Main
api:
 - 3.0.0
 - 3.2.0
version: 5
depends:
 - FormAPI
 - PurePerms
 - EconomyAPI
description: "Hệ thống Nông Dân"
commands:
 farmer:
  description: "Hệ thống nông dân"
  usage: /farmer <help/open>
  default: true
 doiqua:
  description: "Tích điểm đổi quà"
  usage: /doiqua
  default: true
 xemdiem:
   description: "Xem Điểm"
   usage: /xemdiem
   default: true