name: GuideUI
main: NZS\ND\Main
api:
 - 3.0.0
 - 3.2.0
version: 3.0.0
depends:
 - FormAPI
 - PurePerms
description: "Hệ thống Nông Dân"
commands:
 farmer:
  description: "Hệ thống nông dân"
  usage: /farmer <help/open>
  default: true